// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWarsGraphQLNetCore.Data.EntityFramework;

namespace StarWarsGraphQLNetCore.Data.Migrations
{
    [DbContext(typeof(StarWarsContext))]
    [Migration("20180609103422_Full")]
    partial class Full
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StarWarsGraphQLNetCore.Core.Models.Character", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Character");
                });

            modelBuilder.Entity("StarWarsGraphQLNetCore.Core.Models.CharacterEpisode", b =>
                {
                    b.Property<int>("CharacterId");

                    b.Property<int>("EpisodeId");

                    b.HasKey("CharacterId", "EpisodeId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("CharacterEpisodes");
                });

            modelBuilder.Entity("StarWarsGraphQLNetCore.Core.Models.CharacterFriend", b =>
                {
                    b.Property<int>("CharacterId");

                    b.Property<int>("FriendId");

                    b.HasKey("CharacterId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("CharacterFriends");
                });

            modelBuilder.Entity("StarWarsGraphQLNetCore.Core.Models.Episode", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("StarWarsGraphQLNetCore.Core.Models.Planet", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("StarWarsGraphQLNetCore.Core.Models.Droid", b =>
                {
                    b.HasBaseType("StarWarsGraphQLNetCore.Core.Models.Character");

                    b.Property<string>("PrimaryFunction");

                    b.ToTable("Droid");

                    b.HasDiscriminator().HasValue("Droid");
                });

            modelBuilder.Entity("StarWarsGraphQLNetCore.Core.Models.Human", b =>
                {
                    b.HasBaseType("StarWarsGraphQLNetCore.Core.Models.Character");

                    b.Property<int?>("HomePlanetId");

                    b.HasIndex("HomePlanetId");

                    b.ToTable("Human");

                    b.HasDiscriminator().HasValue("Human");
                });

            modelBuilder.Entity("StarWarsGraphQLNetCore.Core.Models.CharacterEpisode", b =>
                {
                    b.HasOne("StarWarsGraphQLNetCore.Core.Models.Character", "Character")
                        .WithMany("CharacterEpisodes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StarWarsGraphQLNetCore.Core.Models.Episode", "Episode")
                        .WithMany("CharacterEpisodes")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StarWarsGraphQLNetCore.Core.Models.CharacterFriend", b =>
                {
                    b.HasOne("StarWarsGraphQLNetCore.Core.Models.Character", "Character")
                        .WithMany("CharacterFriends")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StarWarsGraphQLNetCore.Core.Models.Character", "Friend")
                        .WithMany("FriendCharacters")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StarWarsGraphQLNetCore.Core.Models.Human", b =>
                {
                    b.HasOne("StarWarsGraphQLNetCore.Core.Models.Planet", "HomePlanet")
                        .WithMany("Humans")
                        .HasForeignKey("HomePlanetId");
                });
#pragma warning restore 612, 618
        }
    }
}
